export default {
    extends: [
        'stylelint-config-standard',
        'stylelint-config-recommended',
        'stylelint-config-recommended-vue/scss',
    ],
    plugins: ['stylelint-order', '@stylistic/stylelint-plugin'],
    rules: {
        '@stylistic/indentation': [
            4,
            { baseIndentLevel: 1 },
        ],
        '@stylistic/no-empty-first-line': true,
        '@stylistic/declaration-colon-space-before': 'never',
        '@stylistic/declaration-colon-space-after': 'always',
        '@stylistic/declaration-bang-space-after': 'never',
        '@stylistic/declaration-block-trailing-semicolon': 'always',
        '@stylistic/declaration-block-semicolon-newline-after': 'always',
        '@stylistic/block-opening-brace-space-before': 'always',
        '@stylistic/block-closing-brace-newline-before': 'always',
        '@stylistic/block-closing-brace-newline-after': 'always',
        '@stylistic/block-closing-brace-empty-line-before': 'never',
        '@stylistic/no-extra-semicolons': true,
        'import-notation': 'string',
        'selector-class-pattern': '[a-z]+[A-Z]*',
        'value-keyword-case': ['lower', { ignoreFunctions: ['v-bind'] }],
        'order/properties-order': [
            'content',
            'position',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
            'visibility',
            'box-sizing',
            'overflow',
            'overflow-x',
            'overflow-y',
            'display',
            'justify-content',
            'align-items',
            'align-content',
            'align-self',
            'flex',
            'flex-flow',
            'flex-grow',
            'flex-shrink',
            'flex-wrap',
            'gap',
            'order',
            'float',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-block',
            'margin-inline',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-block',
            'padding-inline',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'border-radius',
            'border',
            'border-color',
            'border-style',
            'border-width',
            'border-top',
            'border-top-color',
            'border-top-style',
            'border-top-width',
            'border-right',
            'border-right-color',
            'border-right-style',
            'border-right-width',
            'border-bottom',
            'border-bottom-color',
            'border-bottom-style',
            'border-bottom-width',
            'border-left',
            'border-left-color',
            'border-left-style',
            'border-left-width',
            'border-spacing',
            'background',
            'background-attachment',
            'background-clip',
            'background-color',
            'background-image',
            'background-origin',
            'background-position',
            'background-repeat',
            'background-size',
            'color',
            'opacity',
            'clip',
            'outline',
            'outline-color',
            'outline-offset',
            'outline-style',
            'outline-width',
            'list-style',
            'list-style-image',
            'list-style-position',
            'list-style-type',
            'columns',
            'column-count',
            'column-fill',
            'column-gap',
            'column-rule',
            'column-rule-color',
            'column-rule-style',
            'column-rule-width',
            'column-span',
            'column-width',
            'vertical-align',
            'text-align',
            'text-align-last',
            'text-decoration',
            'text-decoration-color',
            'text-decoration-line',
            'text-decoration-style',
            'text-indent',
            'text-justify',
            'text-overflow',
            'text-shadow',
            'text-transform',
            'white-space',
            'word-beak',
            'word-spacing',
            'word-wrap',
            'font',
            'font-family',
            'font-size',
            'font-style',
            'font-weight',
            'font-variant',
            'line-height',
            'letter-spacing',
            'transform',
            'transform-origin',
            'transition',
            'transition-delay',
            'transition-duration',
            'transition-property',
            'transition-timing-function',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-delay',
            'animation-fill-mode',
            'animation-direction',
            'animation-iteration-count',
            'animation-play-state',
            'animation-timing-function',
            'cursor',
            'user-select',
        ],
    },
};
